### ISSUE TITLE
Inconsistent definitions in README.md

### ISSUE THREAD

**Issue by craig-shenton** [nhsx/nhs-app-analytics-dashboard#5]
Inconsistent definitions in [README.md](https://github.com/nhsx/nhs-app-analytics-dashboard/blob/main/README.md) for NHS App appointments books & cancelled. 

|     |     |
| --- | --- |
|Users Booking Appointments | Number of App users booking GP appointments in the specified reporting period|
|Appointment Cancellation | Number of appointment cancelled from the NHS App in the specified reporting period|

Think it should be "Number of App users cancelling GP appointments in the specified reporting period"

**Comment by craig-shenton** [comment]
#6 Resolved

**Comment by Arouba** [comment]
All updated
